services:
    _defaults:
        autoconfigure: true
        autowire: true

    lindesbs\MemberDisplay\ContentElement\DisplaySingleMemberController:
        arguments:
            - '@contao.framework'
